name: Example
version: 3.5.0
date: 02/02/2017
description: Example/Template of a GAP Package and Guidelines for Package Authors

authors:
    - name: Werner Nickel
      url: http://www.mathematik.tu-darmstadt.de/~nickel
    - name: Greg Gamble
      url: http://www.math.rwth-aachen.de/~Greg.Gamble
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/

maintainers:
    - name: Greg Gamble
      url: http://www.math.rwth-aachen.de/~Greg.Gamble
    - name: Alexander Konovalov
      url: http://www.cs.st-andrews.ac.uk/~alexk/

GAP: "4.5.3"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/Example
readme: https://gap-packages.github.io/Example/README
packageinfo: https://gap-packages.github.io/Example/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Example/releases/download/v3.5.0/Example-3.5.0.tar.gz

abstract: The <span class="pkgname">Example</span> package, as its name suggests,    is an example of how to create a <span class="pkgname">GAP</span>    package. It has little functionality except for being a package, however,    it contains an extensive appendix with guidelines for package authors.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
